# Generated by Django 5.0.7 on 2024-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscription_stripe_id_subscriptionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
