# Generated by Django 5.0.7 on 2024-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
